techmark/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::auth();

Route::get('/dashboard', 'HomeController@index');
Route::resource('perfil','PerfilController');

Route::group(['prefix'=>'admin','middleware'=>['auth','is_admin','user_on'],'namespace'=>'Admin'], function(){
    /*
     * rutas usuarios
     */
    Route::resource('rol','RolController');
    Route::resource('usuario','UserController');

    /*
     * rutas agenda
     */
    Route::resource('agenda','AgendaController');

    /*
     * todo sucursal
     */
    Route::resource('sucursal','SucursalesController');
    Route::get('getAlmacenes',['as' => 'almacenes_disponibles', 'uses' => 'SucursalesController@getAlmacenes']);

    /*
     * todo compras
     */

    Route::resource('compra','ComprasController');
   // Route::get('addItemsCompra',['as' => 'addItemsCompra', 'uses' => 'ComprasController@addItemsCompra']);
    Route::post('deleteItemsCompra/{id}',['as' => 'deleteItemsCompra', 'uses' => 'IngresosController@deleteItemsCompra']);
    Route::post('confirmCompra/{id}',['as' => 'confirmCompra', 'uses' => 'ComprasController@confirmCompra']);

    Route::resource('compra-credito','ComprasCreditoController');

/*
 * todo ingresos egresos e inventario
 */
    Route::get('inventario/articulos',['as' => 'inventario.articulos', 'uses' => 'InventarioController@articulos']);
    Route::get('ingresos/articulos',['as' => 'ingresos.articulos.index', 'uses' => 'IngresosController@index']);
    Route::get('egresos/articulos',['as' => 'egresos.articulos.index', 'uses' => 'DetalleVentaArticuloController@index']);

    Route::get('ingresos/productos',['as' => 'ingresos.productos.index', 'uses' => 'IngresosProductosController@index']);
    Route::get('egresos/productos',['as' => 'egresos.productos.index', 'uses' => 'DetalleVentaProductoController@index']);
    Route::get('inventario/productos',['as' => 'inventario.productos', 'uses' => 'InventarioController@productos']);

    require __DIR__ . '/routes/diego.php';
    require __DIR__ . '/routes/liss.php';

    /*
     * complementario a productos
     * Asignacion de tallas
     */
    Route::resource('producto/asignacion/talla','AsignacionTallaProducto');
    /*
     * Asignacion de permisos
     */

    Route::post('usuario/{id}/permiso',['as' => 'usuario.permiso', 'uses' => 'UserController@permiso']);
    /*
     * produccion ingresos
     */
    Route::resource('ingresar/productos','IngresosProductosController');
    Route::post('ingresar/productos/workProduccion/{id}/{action}',['as' => 'produccion.workProduccion', 'uses' => 'IngresosProductosController@workProduccion']);
    Route::post('ingresar/productos/changeStateP/{id}',['as' => 'produccion.changeStateP', 'uses' => 'IngresosProductosController@changeStateP']);

    Route::resource('ventas/productos','VentasProductosController');
    Route::post('confirmVentaProducto/{id}/{stado}',['as' => 'confirmVentaProducto', 'uses' => 'VentasProductosController@confirmVenta']);
    Route::delete('destroyItemCar/{id}',['as' => 'vpd.destroyItemCar', 'uses' => 'VentasProductosController@destroyItemCar']);
    Route::resource('ventas/creditos/productos','VentaProductoCreditoController');
    /*
     * todo produccion
     */
    Route::resource('produccion','ProduccionController');

    Route::post('deleteItemsProduccion/{id}',['as' => 'deleteItemsProduccion', 'uses' => 'ProduccionClienteController@deleteItemsProduccion']);
    Route::post('confirmProduccion/{id}',['as' => 'confirmProduccion', 'uses' => 'ProduccionClienteController@confirmProduccion']);

    Route::resource('clientes/produccion','ProduccionClienteController');
    Route::post('clientes/deleteItemsProduccion/{id}',['as' => 'clientes.deleteItemsProduccion', 'uses' => 'ProduccionClienteController@deleteItemsProduccion']);
    Route::post('clientes/confirmProduccion/{id}/{estado}',['as' => 'clientes.confirmProduccion', 'uses' => 'ProduccionClienteController@confirmProduccion']);
    Route::get('clientes/entregarProduccion/{id}',['as' => 'clientes.entregarProduccion', 'uses' => 'ProduccionClienteController@entregar']);
    Route::post('clientes/entregarProduccion/{id}',['as' => 'clientes.entregarProduccion.ok', 'uses' => 'ProduccionClienteController@entregarOk']);
});

Route::group(['prefix'=>'reportes','middleware'=>['auth'],'namespace'=>'Report'], function(){

    // todo usuarios
    Route::get('usuarios','UserReport@index');
    Route::get('usuarios/excel','UserReport@excel');


    require __DIR__ . '/routes/reportdiego.php';
    require __DIR__ . '/routes/reportliss.php';

    Route::get('clientes/producciones','ProduccionesReport@indexClientes');

});





/*
 * servicios para articulos
 */
Route::get('service/getArticuloByCodigo',['as' => 'getArticuloByCodigo', 'uses' => 'ServiceArticulosController@getArticuloByCodigo']);
Route::get('service/getListArticulos',['as' => 'getListArticulos', 'uses' => 'ServiceArticulosController@getListArticulos']);
Route::get('service/showArticle',['as' => 'showArticle', 'uses' => 'ServiceArticulosController@showArticle']);
Route::get('service/showArticleByIngresoId/{id}',['as' => 'showArticleByIngresoId', 'uses' => 'ServiceArticulosController@showArticleByIngresoId']);

/*
 * servicios venta articulos
 */
Route::get('service/getArticuloForVenta',['as' => 'getArticuloForVenta', 'uses' => 'ServiceVentaArticulosController@getArticuloForVenta']);
Route::get('service/getClienteForVenta',['as' => 'getClienteForVenta', 'uses' => 'ServiceVentaArticulosController@getClienteForVenta']);
Route::get('service/showArticleByEgresoId/{id}',['as' => 'showArticleByEgresoId', 'uses' => 'ServiceVentaArticulosController@showArticleByEgresoId']);
Route::post('service/registrarCliente',['as' => 'registrarCliente', 'uses' => 'ServiceVentaArticulosController@registrarCliente']);

/*
 * servicios cotizacion productos
 */

Route::get('service/getListProductosBase',['as' => 'getListProductosBase', 'uses' => 'ServiceDetalleProductoBaseController@getListProductosBase']);
Route::get('service/showDetalleProducto',['as' => 'showDetalleProducto', 'uses' => 'ServiceDetalleProductoBaseController@showDetalleProducto']);
Route::get('service/productoById/{id}',['as' => 'productoById', 'uses' => 'ServiceDetalleProductoBaseController@productoById']);
/*
 * cotizacion
 */
Route::get('service/showArticleByCotizacionId/{id}',['as' => 'showArticleByCotizacionId', 'uses' => 'ServiceCotizacionArticulosController@showArticleByCotizacionId']);
/*
 * produccion
 */
Route::get('service/showArticleByProduccionId/{id}',['as' => 'showArticleByProduccionId', 'uses' => 'ServiceProduccionController@showArticleByProduccionId']);
Route::get('service/showArticleByProduccionId/{id}',['as' => 'clientes.showArticleByProduccionId', 'uses' => 'ServiceProduccionController@CArticleByProduccionId']);
/*
 * servicios ingresos productos producidos
 */
Route::get('service/productByCode',['as' => 'productByCode', 'uses' => 'ServiceProductosController@productByCode']);
Route::post('service/priceByIdProduct',['as' => 'priceByIdProduct', 'uses' => 'ServiceProductosController@priceByIdProduct']);
Route::get('service/productByRowId',['as' => 'productByRowId', 'uses' => 'ServiceProductosController@productByRowId']);
Route::get('service/getListProductos',['as' => 'getListProductos', 'uses' => 'ServiceProductosController@getListProductos']);
Route::get('service/showProductoSearch',['as' => 'showProductoSearch', 'uses' => 'ServiceProductosController@showProductoSearch']);
Route::get('service/ventaProductobyRow',['as' => 'ventaProductobyRow', 'uses' => 'ServiceProductosController@ventaProductobyRow']);
/*
 * rutas sucursal
 */
Route::group(['prefix'=>'s','middleware'=>['auth','user_on'],'namespace'=>'Sucursal'], function(){

    Route::resource('cliente','ClienteController');
    require __DIR__ . '/routes/sdiego.php';
   // require __DIR__ . '/routes/sliss.php';
    Route::resource('caja','CajaController');

});

techmark/resources/views/theme/ubold/sidebar/admin.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>

                <li class="text-muted menu-title">Navegacion</li>

                <li class="has_sub">
                    <a href="{{url('dashboard')}}" class="waves-effect"><i class="ti-home"></i> <span> Inicio </span> </a>

                </li>
                <li class="has_sub">
                    <a href="{{route('admin.agenda.index')}}" class="waves-effect"><i class=" icon-notebook"></i> <span> Agenda </span> </a>

                </li>
                <li class="has_sub">
                    <a href="{{route('admin.caja.index')}}" class="waves-effect"><i class=" typcn typcn-device-desktop"></i> <span> Caja </span> </a>

                </li>
                <li class="has_sub">
                    <a href="{{route('admin.gasto.index')}}" class="waves-effect"><i class=" icon-wallet"></i> <span> Gastos </span> </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="icon-basket"></i><span class="label label-primary pull-right">2</span> <span> Ventas </span>  </a>
                    <ul class="list-unstyled">
                        <li class="text-muted menu-title">ARTICULOS</li>
                        <li><a href="{{route('admin.venta_art.index')}}">Vender Articulos</a></li>
                        <li><a href="{{route('admin.venta-credito-art.index')}}">Ventas al Credito</a></li>
                        <li class="text-muted menu-title">PRODUCTOS</li>
                        <li><a href="{{route('admin.ventas.productos.index')}}">Vender Productos</a></li>
                        <li><a href="{{route('admin.ventas.creditos.productos.index')}}">Ventas al Credito</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class=" icon-note"></i><span class="label label-primary pull-right">2</span> <span> Cotizaciones </span>  </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('admin.cotizacion.index')}}">Articulos</a></li>
                        <li><a href="{{route('admin.cot_producto.index')}}">Productos</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class=" icon-handbag"></i><span class="label label-primary pull-right">5</span> <span> Articulos </span>  </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('admin.articulo.index')}}">Articulos</a></li>
                        <li><a href="{{route('admin.categoria.index')}}">Categorias Articulos</a></li>
                        <li><a href="{{route('admin.marca.index')}}">Marcas</a></li>
                        <li><a href="{{route('admin.material.index')}}">Materiales</a></li>
                        <li><a href="{{route('admin.unidad.index')}}">Unidades</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class=" icon-puzzle"></i><span class="label label-primary pull-right">4</span> <span> Productos </span>  </a>
                    <ul class="list-unstyled">
                        <li class="text-muted menu-title">PRODUCTOS VENTA</li>
                        <li><a href="{{route('admin.producto.index')}}">Producto</a></li>
                        <li class="text-muted menu-title">PRODUCTOS COTIZACIONES</li>
                        <li><a href="{{route('admin.prodbase.index')}}">Nombre Producto Base</a></li>
                        <li><a href="{{route('admin.detprodbase.index')}}">Detallar Producto Base</a></li>
                        <li class="text-muted menu-title">MANTENIMIENTO</li>
                        <li><a href="{{route('admin.talla.index')}}">Tallas</a></li>

                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class=" ti-notepad"></i><span class="label label-primary pull-right">6</span> <span> Inventario </span>  </a>
                    <ul class="list-unstyled">
                        <li class="text-muted menu-title">ARTICULOS</li>
                        <li><a href="{{route('inventario.articulos')}}">Articulos</a></li>
                        <li><a href="{{route('ingresos.articulos.index')}}">Ingresos Articulos</a></li>
                        <li><a href="{{route('egresos.articulos.index')}}">Egresos Articulos</a></li>

                        <li class="text-muted menu-title">PRODUCTOS</li>
                        <li><a href="{{route('inventario.productos')}}">Productos</a></li>
                        <li><a href="{{route('ingresos.productos.index')}}">Ingresos Productos</a></li>
                        <li><a href="{{route('egresos.productos.index')}}">Egresos Productos</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="icon-people"></i><span class="label label-primary pull-right">2</span> <span> Usuarios & Roles </span>  </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('admin.usuario.index')}}">Usuarios</a></li>
                        <li><a href="{{route('admin.rol.index')}}">Rol</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="{{route('admin.cliente.index')}}" class="waves-effect"><i class=" icon-user-follow"></i> <span> Clientes </span> </a>
                </li>
                <li class="has_sub">
                    <a href="{{route('admin.trabajador.index')}}" class="waves-effect"><i class=" icon-user-following"></i> <span> Trabajadores </span> </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-direction"></i><span class="label label-primary pull-right">2</span> <span> Sucursal  & Almacen</span>  </a>
                    <ul class="list-unstyled">
                        <a href="{{route('admin.sucursal.index')}}">Sucursales</a>
                        <a href="{{route('admin.almacen.index')}}">Almacenes</a>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-truck"></i><span class="label label-primary pull-right">2</span> <span> Compras </span>  </a>
                    <ul class="list-unstyled">
                        <a href="{{route('admin.compra.index')}}">Registrar Compra</a>
                        <a href="{{route('admin.compra-credito.index')}}">Compras al Credito</a>
                        <a href="{{route('admin.proveedor.index')}}">Proveedores</a>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-cog fa-spin"></i><span class="label label-primary pull-right">2</span> <span> Producción </span>  </a>
                    <ul class="list-unstyled">
                        <a href="{{route('admin.produccion.index')}}">Productos Venta</a>
                        <a href="{{route('admin.clientes.produccion.index')}}">Productos Cliente</a>
                    </ul>
                </li>
                <li class="text-muted menu-title">Configuraciones Sistemas</li>
                <li class="has_sub">
                    <a href="{{route('admin.ciudad.index')}}" class="waves-effect"><i class=" icon-location-pin"></i> <span> Ciudades </span> </a>
                </li>
                {{--<li class="text-muted menu-title">Rutas Liss</li>--}}
                {{--@include('theme.ubold.sidebar.liss')--}}
                {{--<li class="text-muted menu-title">Rutas Diego</li>--}}
                {{--@include('theme.ubold.sidebar.diego')--}}
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

techmark/resources/views/theme/ubold/sidebar/sucursal.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Navegacion</li>
                <li class="has_sub">
                    <a href="{{url('dashboard')}}" class="waves-effect"><i class="ti-home"></i> <span> Inicio </span> </a>
                </li>
                <li class="has_sub">
                    <a href="{{route('s.gasto.index')}}" class="waves-effect"><i class=" icon-wallet"></i> <span> Gastos </span> </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="icon-basket"></i><span class="label label-primary pull-right">4</span> <span> Ventas </span>  </a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('s.venta_art.index')}}">Venta Articulos</a></li>
                        <li ><a href="{{route('s.ventas.productos.index')}}">Venta Productos</a></li>
                        <li><a href="{{route('s.venta-credito-art.index')}}">Credito Venta Articulos</a></li>
                        <li><a href="{{route('s.ventas.creditos.productos.index')}}">Venta Credito Productos</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class=" icon-handbag"></i><span class="label label-primary pull-right">4</span> <span> Inventario </span>  </a>
                <ul class="list-unstyled">
                    <li class="text-muted menu-title">ARTICULOS</li>
                    <li><a href="{{route('s.inventario.articulos')}}"> Articulos</a></li>
                    <li><a href="{{route('s.ingresos.articulos.index')}}">Ingresos Articulos</a></li>
                    <li><a href="{{route('s.egresos.articulos.index')}}">Egresos Articulos</a></li>
                    <li class="text-muted menu-title">PRODUCTOS</li>
                    <li ><a href="{{route('s.inventario.productos')}}"> Productos</a></li>
                    <li><a href="{{route('s.ingresos.productos.index')}}">Ingresos Productos</a></li>
                    <li><a href="{{route('s.egresos.productos.index')}}">Egresos Productos</a></li>
                </ul>
                </li>
                <li class="has_sub">
                <a href="javascript:void(0);" class="waves-effect"><i class=" icon-note"></i><span class="label label-primary pull-right">2</span> <span> Cotizaciones </span>  </a>
                <ul class="list-unstyled">
                    <li ><a href="{{route('s.cotizacion.index')}}"> Articulos</a></li>
                    <li ><a href="{{route('s.cot_producto.index')}}"> Productos</a></li>
                </ul>
                </li>
                <li class="has_sub">
                    <a href="{{route('s.cliente.index')}}" class="waves-effect"><i class="icon-people"></i> <span> Cliente </span> </a>
                </li>



            </ul>

        </div>
        <div class="clearfix"></div>
    </div>
</div>